version: '3'
services:
  app:
    container_name: bonodb
    restart: always
    build: .
    ports:
      - '3000:3000'
    links:
      - mongo
  mongo:
    container_name: localhost
    image: mongo
    ports:
      - '27017:27017'